{
 "cells": [
  {
   "cell_type": "code",
   "execution_count": 1,
   "id": "ede2b375-ff67-49bd-94bd-f3769c601ba5",
   "metadata": {},
   "outputs": [
    {
     "ename": "NameError",
     "evalue": "name '__file__' is not defined",
     "output_type": "error",
     "traceback": [
      "\u001b[31m---------------------------------------------------------------------------\u001b[39m",
      "\u001b[31mNameError\u001b[39m                                 Traceback (most recent call last)",
      "\u001b[36mCell\u001b[39m\u001b[36m \u001b[39m\u001b[32mIn[1]\u001b[39m\u001b[32m, line 26\u001b[39m\n\u001b[32m     20\u001b[39m     \u001b[38;5;28;01mreturn\u001b[39;00m \u001b[33m\"\u001b[39m\u001b[33mOK\u001b[39m\u001b[33m\"\u001b[39m\n\u001b[32m     22\u001b[39m \u001b[38;5;66;03m# ==========================================================\u001b[39;00m\n\u001b[32m     23\u001b[39m \u001b[38;5;66;03m# Load Model\u001b[39;00m\n\u001b[32m     24\u001b[39m \u001b[38;5;66;03m# ==========================================================\u001b[39;00m\n\u001b[32m---> \u001b[39m\u001b[32m26\u001b[39m BASE_DIR = os.path.dirname(os.path.abspath(\u001b[34;43m__file__\u001b[39;49m))\n\u001b[32m     28\u001b[39m MODEL_PATH = os.path.join(\n\u001b[32m     29\u001b[39m     BASE_DIR,\n\u001b[32m     30\u001b[39m     \u001b[33m\"\u001b[39m\u001b[33mmodel\u001b[39m\u001b[33m\"\u001b[39m,\n\u001b[32m     31\u001b[39m     \u001b[33m\"\u001b[39m\u001b[33mrandom_forest.pkl\u001b[39m\u001b[33m\"\u001b[39m\n\u001b[32m     32\u001b[39m )\n\u001b[32m     34\u001b[39m model = joblib.load(MODEL_PATH)\n",
      "\u001b[31mNameError\u001b[39m: name '__file__' is not defined"
     ]
    }
   ],
   "source": [
    "from flask import Flask, render_template, request\n",
    "import pandas as pd\n",
    "import joblib\n",
    "import shap\n",
    "import os\n",
    "\n",
    "\n",
    "# ==========================================================\n",
    "# Flask App\n",
    "# ==========================================================\n",
    "\n",
    "app = Flask(\n",
    "    __name__,\n",
    "    template_folder=\"website/templates\",\n",
    "    static_folder=\"website/static\"\n",
    ")\n",
    "\n",
    "@app.route(\"/health\")\n",
    "def health():\n",
    "    return \"OK\"\n",
    "    \n",
    "# ==========================================================\n",
    "# Load Model\n",
    "# ==========================================================\n",
    "\n",
    "BASE_DIR = os.path.dirname(os.path.abspath(__file__))\n",
    "\n",
    "MODEL_PATH = os.path.join(\n",
    "    BASE_DIR,\n",
    "    \"model\",\n",
    "    \"random_forest.pkl\"\n",
    ")\n",
    "\n",
    "model = joblib.load(MODEL_PATH)\n",
    "\n",
    "print(\"Random Forest Model Loaded Successfully!\")\n",
    "\n",
    "\n",
    "# ==========================================================\n",
    "# SHAP Explainer\n",
    "# ==========================================================\n",
    "\n",
    "explainer = shap.TreeExplainer(model)\n",
    "\n",
    "print(\"SHAP Explainer Created Successfully!\")\n",
    "# ==========================================================\n",
    "# Home Page\n",
    "# ==========================================================\n",
    "\n",
    "@app.route(\"/\")\n",
    "def home():\n",
    "    return render_template(\"index.html\")\n",
    "\n",
    "\n",
    "# ==========================================================\n",
    "# Prediction\n",
    "# ==========================================================\n",
    "\n",
    "@app.route(\"/predict\", methods=[\"POST\"])\n",
    "def predict():\n",
    "\n",
    "    # ---------------------------------------\n",
    "    # Read User Input\n",
    "    # ---------------------------------------\n",
    "\n",
    "    age = int(request.form[\"Age\"])\n",
    "    gender = int(request.form[\"Gender\"])\n",
    "    polyuria = int(request.form[\"Polyuria\"])\n",
    "    polydipsia = int(request.form[\"Polydipsia\"])\n",
    "    sudden_weight_loss = int(request.form[\"SuddenWeightLoss\"])\n",
    "    weakness = int(request.form[\"Weakness\"])\n",
    "    polyphagia = int(request.form[\"Polyphagia\"])\n",
    "    genital_thrush = int(request.form[\"GenitalThrush\"])\n",
    "    visual_blurring = int(request.form[\"VisualBlurring\"])\n",
    "    itching = int(request.form[\"Itching\"])\n",
    "    irritability = int(request.form[\"Irritability\"])\n",
    "    delayed_healing = int(request.form[\"DelayedHealing\"])\n",
    "    partial_paresis = int(request.form[\"PartialParesis\"])\n",
    "    muscle_stiffness = int(request.form[\"MuscleStiffness\"])\n",
    "    alopecia = int(request.form[\"Alopecia\"])\n",
    "    obesity = int(request.form[\"Obesity\"])\n",
    "\n",
    "    # ---------------------------------------\n",
    "    # Convert Input into DataFrame\n",
    "    # ---------------------------------------\n",
    "\n",
    "    patient = pd.DataFrame({\n",
    "\n",
    "        \"Age\":[age],\n",
    "        \"Gender\":[gender],\n",
    "        \"Polyuria\":[polyuria],\n",
    "        \"Polydipsia\":[polydipsia],\n",
    "        \"SuddenWeightLoss\":[sudden_weight_loss],\n",
    "        \"Weakness\":[weakness],\n",
    "        \"Polyphagia\":[polyphagia],\n",
    "        \"GenitalThrush\":[genital_thrush],\n",
    "        \"VisualBlurring\":[visual_blurring],\n",
    "        \"Itching\":[itching],\n",
    "        \"Irritability\":[irritability],\n",
    "        \"DelayedHealing\":[delayed_healing],\n",
    "        \"PartialParesis\":[partial_paresis],\n",
    "        \"MuscleStiffness\":[muscle_stiffness],\n",
    "        \"Alopecia\":[alopecia],\n",
    "        \"Obesity\":[obesity]\n",
    "\n",
    "    })\n",
    "\n",
    "    # ---------------------------------------\n",
    "    # Prediction\n",
    "    # ---------------------------------------\n",
    "\n",
    "    prediction = model.predict(patient)[0]\n",
    "\n",
    "    probability = model.predict_proba(patient)[0][1]\n",
    "\n",
    "    # ---------------------------------------\n",
    "    # SHAP Values\n",
    "    # ---------------------------------------\n",
    "\n",
    "    shap_values = explainer.shap_values(patient)\n",
    "\n",
    "    # Handle SHAP version differences\n",
    "    if isinstance(shap_values, list):\n",
    "        diabetes_shap = shap_values[1][0]\n",
    "    else:\n",
    "        diabetes_shap = shap_values[0][:, 1]\n",
    "    \n",
    "    contribution = pd.DataFrame({\n",
    "    \n",
    "        \"Feature\": patient.columns,\n",
    "        \"Value\": patient.iloc[0].values,\n",
    "        \"SHAP\": diabetes_shap\n",
    "    \n",
    "    })\n",
    "\n",
    "    contribution[\"Absolute SHAP\"] = contribution[\"SHAP\"].abs()\n",
    "\n",
    "    contribution[\"Contribution (%)\"] = (\n",
    "        contribution[\"Absolute SHAP\"] /\n",
    "        contribution[\"Absolute SHAP\"].sum()\n",
    "    ) * 100\n",
    "\n",
    "    contribution = contribution.sort_values(\n",
    "        by=\"Contribution (%)\",\n",
    "        ascending=False\n",
    "    )\n",
    "\n",
    "    # ---------------------------------------\n",
    "    # Sort Features by SHAP Contribution\n",
    "    # ---------------------------------------\n",
    "    \n",
    "    contribution = contribution.sort_values(\n",
    "        by=\"Contribution (%)\",\n",
    "        ascending=False\n",
    "    )\n",
    "    \n",
    "    # ---------------------------------------\n",
    "    # Convert User Inputs to Readable Values\n",
    "    # ---------------------------------------\n",
    "    \n",
    "    display_values = []\n",
    "    \n",
    "    for feature, value in zip(\n",
    "        contribution[\"Feature\"],\n",
    "        contribution[\"Value\"]\n",
    "    ):\n",
    "    \n",
    "        if feature == \"Gender\":\n",
    "            display_values.append(\"Male\" if value == 1 else \"Female\")\n",
    "    \n",
    "        elif feature == \"Age\":\n",
    "            display_values.append(int(value))\n",
    "    \n",
    "        else:\n",
    "            display_values.append(\"Yes\" if value == 1 else \"No\")\n",
    "    \n",
    "    # ---------------------------------------\n",
    "    # Prediction Text\n",
    "    # ---------------------------------------\n",
    "    \n",
    "    if prediction == 1:\n",
    "        result = \"Positive\"\n",
    "    else:\n",
    "        result = \"Negative\"\n",
    "    \n",
    "    # ---------------------------------------\n",
    "    # Risk Level\n",
    "    # ---------------------------------------\n",
    "    \n",
    "    if probability < 0.30:\n",
    "        risk = \"Low\"\n",
    "    elif probability < 0.70:\n",
    "        risk = \"Moderate\"\n",
    "    else:\n",
    "        risk = \"High\"\n",
    "\n",
    "    # ---------------------------------------\n",
    "    # Send Data to HTML\n",
    "    # ---------------------------------------\n",
    "    \n",
    "    return render_template(\n",
    "    \n",
    "        \"result.html\",\n",
    "    \n",
    "        prediction=result,\n",
    "    \n",
    "        probability=round(probability * 100, 2),\n",
    "    \n",
    "        risk=risk,\n",
    "    \n",
    "        feature_names=contribution[\"Feature\"].tolist(),\n",
    "    \n",
    "        input_values=display_values,\n",
    "    \n",
    "        feature_values=contribution[\"Contribution (%)\"].round(2).tolist()\n",
    "    \n",
    "    )\n",
    "\n",
    "\n",
    "# ==========================================================\n",
    "# Run Flask\n",
    "# ==========================================================\n",
    "\n",
    "if __name__ == \"__main__\":\n",
    "    app.run(\n",
    "        host=\"0.0.0.0\",\n",
    "        port=5000,\n",
    "        debug=False\n",
    "    )"
   ]
  },
  {
   "cell_type": "code",
   "execution_count": null,
   "id": "b5d6447d-fd3d-40f0-88fd-8ee1256e4ef2",
   "metadata": {},
   "outputs": [],
   "source": []
  }
 ],
 "metadata": {
  "kernelspec": {
   "display_name": "Python [conda env:base] *",
   "language": "python",
   "name": "conda-base-py"
  },
  "language_info": {
   "codemirror_mode": {
    "name": "ipython",
    "version": 3
   },
   "file_extension": ".py",
   "mimetype": "text/x-python",
   "name": "python",
   "nbconvert_exporter": "python",
   "pygments_lexer": "ipython3",
   "version": "3.13.9"
  }
 },
 "nbformat": 4,
 "nbformat_minor": 5
}
